---
title: CASTOR
timezone: UTC
collections:
subtitle: Software Days
url: https://castor-software-days-2020.github.io/
baseurl: ''
email: sw-days-organizers@kth.se
description: Three days about software technology for students, developers, researchers
  and all software passionates
social:
- title: envelope
  url: mailto:sw-days-organizers@kth.se
- title: globe
  url: https://www.castor.kth.se
- title: twitter
  url: https://twitter.com/CastorKth
markdown: kramdown
